project 'DevSummit.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DevSummit' do
    use_frameworks!

    pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'


    target 'DevSummitTests' do
        inherit! :search_paths
        end

    end

    target 'DevSummit-tvOS' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    target 'DevSummit-tvOSTests' do
        inherit! :search_paths
      # Pods for testing
    end

end
