project 'app.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app
    pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
    pod 'Fabric'
    pod 'Firebase/Core'
    pod 'FirebaseMessaging'
    pod 'Crashlytics'
    
  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app-tvOS

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
