export default {
  // New order
  total: 'Total price',
  useReferalCode: 'Use referal code',
  checkCode: 'Check referal code',
  used: 'You already used referal code before',
  quotaExceeded: 'The quota of referal code has reach the limit',
  codeInvalid: 'Referal code is not valid',
  codeSuccess: 'Referal code used',
  referalLimit: '* Referal code is available for 1 ticket only',
  referalInfo: 'REFERAL INFO',
  referalCode: 'Referal code',
  owner: 'Owner',
  totalDiscount: 'Total discount',
  totalAfterDiscount: 'Total after discount',
  placeOrder: 'Place order',

  // Order detail
  confirmUpdate: 'Are you sure to update this order',
  orderNumber: 'Order ID',
  orderDate: 'Order date',
  expiredDate: 'Expired time',
  confirmPayment: 'Payment confirmation',
  confirmPaymenOrder: 'Confirm payment order',
  includeCode: 'Including this code :',
  paymentCode: 'Payment code',
  instruction1: 'Please pay the total bill',
  instruction2: 'to account number',
  instruction3: 'from Veritrans',
  attention: 'Important: the payment deadline is 1 (one) hour. If the deadline exceeded then your order will be automatically canceled.',
  updateProof: 'Upload Payment Proof',
  reuploadProof: 'Re-upload Payment Proof',
  noProof: 'No payment proof yet',
  downloadAcc: 'Download Account Reference',

  // Ticket list
  ticketNumber: 'Ticket No.',
  noTicket: 'You have no tickets, please order or try to refresh',
  QRInstruction: 'You can checkin using this QR code',
  refresh: 'Refresh',
  myOrder: 'My orders',
  pending: 'orders is pending',
  allTicket: 'All your ticket orders shows up here',
  ticketOrder: 'Ticket orders',
  redeem: 'Redeem code',
  proceedPaymentTitle: 'Proceed to pay this ticket?',
  proceedPaymentMessage: 'We are about to take you to the payment page. Click yes if you\'re ready to get your ticket',
  proceedYes: 'Yes',
  proceedNo: 'No'
};
