export default {
  title: 'Privacy Policy',
  content1: 'This page informs you of our policies regarding the collection, use and disclosure of Personal Information when you use our Service. We will not use or share your information with anyone except as described in this Privacy Policy. We use your Personal Information for providing and improving the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.',
  title2: 'Information Collection And Use',
  content2: 'While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to, your email, name or phone number (“Personal Information”). We collect this information for the purpose of providing the Service, identifying and communicating with you, responding to your requests/inquiries, servicing your purchase orders, and improving our services. If you subscribe or purchase any product or course offered by the Company or one of its subsidiaries, you will enter into a new agreement with privacy provisions. In that case, the new agreement will contain new terms that apply to the information you provide us in the course of your use of the product of course.',
  title3: 'Service Providers',
  content3: 'We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Service-related services and/or to assist us in analyzing how our Service is used. These third parties have access to your Personal Information only to perform specific tasks on our behalf and are obligated not to disclose or use your information for any other purpose.',
  title4: 'Communications',
  content4: 'We may use your Personal Information to contact you with notifications and post, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.',
  title5: 'Compliance With Laws',
  content5: 'We will disclose your Personal Information where required to do so by law or subpoena or if we believe that such action is necessary to comply with the law and the reasonable requests of law enforcement or to protect the security or integrity of our Service.',
  title6: 'Security',
  content6: 'The security of your Personal Information is important to us, and we strive to implement and maintain reasonable, commercially acceptable security procedures and practices appropriate to the nature of the information we store, in order to protect it from unauthorized access, destruction, use, modification, or disclosure. We may store your Log Data for an indefinite amount of time. If you want us to destroy your Log Data or Personal Information, please contact us at the address noted below. However, please be aware that no method of transmission over the internet, or method of electronic storage is 100% secure and we are unable to guarantee the absolute security of the Personal Information we have collected from you.',
  title7: 'Links To Other Sites',
  content7: 'Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over, and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
  title8: 'Contact Us',
  content8: 'Refactory \nJl. Ir. H. Juanda 84, Eduplex Indonesia 3rd Floor \nBandung, 40191, Indonesia.',
  lastUpdated: 'Last updated: September 26th, 2017'
};
